name: Deploy to domainhotelli.fi

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Lataa koodi
        uses: actions/checkout@v4

      - name: Lähetä tiedostot FTP:llä
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/
          dangerous-clean-slate: true
          protocol: ftp
          port: 21
